### ISSUE TITLE
What is the password actual string?

### ISSUE THREAD

**Issue by mikeerickson** [coderello/laravel-populated-factory#1]
Nice package!

Curious, what is the plain value for the password matching the example?  I am assuming it is something like `password` or `secret` :-)

```php
'password' => '$2y$10$uTDnsRa0h7wLppc8/vB9C.YqsrAZwhjCgLWjcmpbndTmyo1k5tbRC',
```

Perhaps using the following would be better?

```php
'password' => bcrypt('password'),
```

**Comment by hivokas** [comment]
The plain value is `secret`. I've decided to put there already encrypted password in order to decrease the seeding time by avoiding the password encrypting for each model.

**Comment by mikeerickson** [comment]
Makes sense to me, I can live with that reason 🤓
