### ISSUE TITLE
Unknown database type enum 

### ISSUE THREAD

**Issue by mrosama** [coderello/laravel-populated-factory#14]
Unknown database type enum requested, Doctrine\DBAL\Platforms\MySQL57Platform may not support it. ??

**Comment by hivokas** [comment]
@mrosama thanks for reporting the issue! I've pushed the fix (https://github.com/coderello/laravel-populated-factory/commit/f078a315487db65e31eaf62ff501f97d6ebc4fee) and published the release (https://github.com/coderello/laravel-populated-factory/releases/tag/0.3.2).

Could you try to install the latest version of the package and try again?

**Comment by mrosama** [comment]
@hivokas  it is working no error , but it is escape enum type 

migration file

  Schema::create('todos', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('title');
            $table->enum('status',['draft','published','archived'])->default('draft');
            $table->unsignedInteger('level')->default(0);
            $table->boolean('published')->default(0);
            $table->timestamps();
        });

-----
generate result
----


$factory->define(\App\Todo::class, function (Faker $faker) {
    return [
        'title' => $faker->text(47),
        'level' => $faker->numberBetween(0, 4294967295),
        'published' => $faker->boolean(50),
        'created_at' => $faker->dateTime,
        'updated_at' => $faker->dateTime,
    ];
});

**Comment by hivokas** [comment]
@mrosama do you have any ideas on how to get the list of possible enum values?
