### ISSUE TITLE
Support For Laravel Six

### ISSUE THREAD

**Issue by marvinhosea** [coderello/laravel-populated-factory#4]
Problem 1
    - Installation request for coderello/laravel-populated-factory ^0.1.0 -> satisfiable by coderello/laravel-populated-factory[0.1.0].
    - Conclusion: remove laravel/framework v6.9.0
    - Conclusion: don't install laravel/framework v6.9.0
    - coderello/laravel-populated-factory 0.1.0 requires laravel/framework 5.5.*|5.6.*|5.7.*|5.8.* -> satisfiable by laravel/framework[5.5.x-dev, 5.6.x-dev, 5.7.x-dev, 5.8.x-dev].
    - Can only install one of: laravel/framework[5.5.x-dev, v6.9.0].
    - Can only install one of: laravel/framework[5.6.x-dev, v6.9.0].
    - Can only install one of: laravel/framework[5.7.x-dev, v6.9.0].
    - Can only install one of: laravel/framework[5.8.x-dev, v6.9.0].
    - Installation request for laravel/framework (locked at v6.9.0, required as ^6.2) -> satisfiable by laravel/framework[v6.9.0].

**Comment by hivokas** [comment]
Could you submit a PR please?

**Comment by hivokas** [comment]
@marvinhosea I've added Laravel 6 support
