### ISSUE TITLE
InvalidArgumentException : Unknown formatter "companyName"

### ISSUE THREAD

**Issue by chatii** [coderello/laravel-populated-factory#8]
https://github.com/coderello/laravel-populated-factory/blob/920cec0662ffc7994e8c0a5f061b5b176f8d5a74/src/FakeValueExpressionGuesser.php#L83

Faker no have `companyName` property. (I tried Faker `"version": "v1.9.1"`)

ref: https://github.com/fzaninotto/Faker#fakerprovideren_uscompany

**Comment by hivokas** [comment]
Hm. Then let's change `companyName` to `company`.
Do you have a time to submit a PR for that?

**Comment by hivokas** [comment]
Fixed #12
